name: Publish package

on:
  push:
    tags:
      - "*"
    
env:
  name: ${{github.event.repository.name}}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get clean version
        run: |
          echo cleanVersion=$(echo ${{github.ref_name}} | sed s/v//g) >> $GITHUB_ENV
      - name: Check that version matches
        run: |
          if [[ "$(grep -Po "\d+\.\d+\.\d+" $(find ./ -name mod.json))" != "${{ env.cleanVersion }}" ]]; then
            echo "::debug::${{env.cleanVersion}}"
            echo "::debug::$(cat $(find ./ -name mod.json ))"
            echo "::error::Version in mod.json does not match tag version"
            exit 1
          fi
  publish:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - uses: actions/checkout@v4
      - name: Upload Thunderstore Package
        uses: GreenTF/upload-thunderstore-package@v3.1
        with:
          community: northstar
          namespace: ${{ github.repository_owner }}
          name: ${{ env.name }}
          version: ${{ github.ref_name }}
          description: Randomize your sensitivity every kill
          token: ${{ secrets.TS_KEY }} 
          wrap: mods/${{ github.repository_owner }}.${{ env.name }}
          deps: "S2Mods-ClientKillCallback@2.0.1"
          categories: "mods client-side"
